### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by aiguo112** [guoxiliu/VideoStream-NS3#1]
Hi, thank you so much for your code, and installation guide. I am facing issues on step 2. I have successfully installed NS3 and have run example tutorial first.cc. 

I copied all the files from your repo to ns3.33 folder. After copying the files, when I run **./waf** , the build is crashed with the following error. Can you please guide me where I am making a mistake? 

Build failed
 -> task in 'three-gpp-http-example' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-bridge-one-hop' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-multicast' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-one-subnet' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-broadcast' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-packet-socket' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-star' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-raw-ip-socket' failed with exit status 1 (run with -v to display more information)
 -> task in 'fd-emu-onoff' failed with exit status 1 (run with -v to display more information)
 -> task in 'fd-emu-tc' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-ping' failed with exit status 1 (run with -v to display more information)
 -> task in 'csma-bridge' failed with exit status 1 (run with -v to display more information)
 -> task in 'fd2fd-onoff' failed with exit status 1 (run with -v to display more information)
 -> task in 'realtime-fd2fd-onoff' failed with exit status 1 (run with -v to display more information)
 -> task in 'dsdv-manet' failed with exit status 1 (run with -v to display more information)
 -> task in 'dsr' failed with exit status 1 (run with -v to display more information)

Complete Screenshot is attached. 

![Screenshot from 2021-05-07 22-44-39](https://user-images.githubusercontent.com/81693706/117467045-e99fb080-af85-11eb-8370-2500815c624a.png)

**Comment by guoxiliu** [comment]
Did you try to build ns-3 without `VideoStream` application? Not sure if it is related to the version, but we used `ns-3.30` for the project.

**Comment by aiguo112** [comment]
After changing the NS3 version from **3.33 to 3.30** it worked fine. Thank you.
